# Generated by Django 4.2.1 on 2023-05-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_url', models.CharField(max_length=2000)),
                ('short_url', models.CharField(max_length=250, unique=True)),
                ('visits', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
